import { FormField } from '../../components/form-field'
import type { Student } from '../../types/student'
import type { ReactNode } from 'react'

export function createAuthorizationFormSections(student: Student): ReactNode[] {
  return [
    <><div className="notice sensitive">Esta ficha es confidencial y está destinada al equipo de salud escolar para apoyar la atención durante la jornada y en caso de emergencia.</div><div className="field-grid three"><FormField label="Código AMIE" placeholder="08H00276" /><FormField label="Nombre del estudiante (apellidos y nombres)" required placeholder={student.name} /><FormField label="Fecha de nacimiento" type="date" /><FormField label="Dirección del domicilio" /><FormField label="Nombre del representante o familiar responsable" /><FormField label="Parentesco" /><FormField label="Teléfono fijo" type="tel" /><FormField label="Teléfono celular" type="tel" /><FormField label="Año lectivo" placeholder="20__ – 20__" /></div></>,
    <><div className="field-grid"><FormField label="¿Posee seguro médico?" options={['Sí', 'No']} /><FormField label="Nombre del seguro (IESS, ISSFA, ISSPOL u otro)" /><FormField label="Establecimiento de salud al que normalmente acude" /><FormField label="Grupo sanguíneo y factor RH" options={['A+', 'A−', 'B+', 'B−', 'AB+', 'AB−', 'O+', 'O−', 'No conoce']} /><FormField label="¿El estudiante sabe nadar?" options={['Sí', 'No']} /></div><h3>Contactos de urgencia</h3><p className="helper">Orden de importancia. Indique obligatoriamente al menos un número fijo de contacto.</p>{[1, 2].map(n => <div className="contact-card" key={n}><b>{n}. Contacto prioritario</b><div className="field-grid three"><FormField label="Nombre del representante o familiar responsable" /><FormField label="Parentesco" /><FormField label="Teléfono fijo" type="tel" required={n === 1} /><FormField label="Teléfono celular" type="tel" /></div></div>)}</>,
    <><div className="notice sensitive">No incluya información médica real en esta demostración. Los campos se dejan vacíos para completar posteriormente.</div><div className="field-grid"><FormField label="¿Ha sido diagnosticado con alguna enfermedad que considere importante?" options={['Sí', 'No']} /><FormField label="Diagnósticos (si corresponde)" /></div><FormField label="¿Qué medicamentos usa?" type="textarea" /><div className="field-grid"><FormField label="¿Ha sido sometido a cirugías previas?" options={['Sí', 'No']} /><FormField label="Detalle (si corresponde)" /></div><div className="field-grid"><FormField label="¿Tiene alergias?" options={['Sí', 'No']} /><FormField label="Detalle (si corresponde)" /></div><FormField label="Terapia médica específica (ej. transfusión de sangre)" type="textarea" /><FormField label="Otras condiciones médicas importantes" type="textarea" /><FormField label="Si existe una condición médica importante, explíquela" type="textarea" /></>,
    <><div className="notice legal">Yo, con número de cédula (nombre y apellido del representante), autorizo que mi representado, con número de cédula, reciba atención médica escolar y, en caso de urgencia, sea trasladado al establecimiento de salud respectivo en el Distrito o fuera de él si es necesario. Declaro que la información consignada en esta ficha corresponde a la realidad y me comprometo a comunicar por escrito a la Unidad Educativa cualquier modificación. La ficha también contempla informar si, por razones culturales o religiosas, no se autoriza algún tratamiento o terapia médica específica.</div><p className="helper">Representación del texto institucional; la firma se completa fuera de esta interfaz.</p><label className="declaration"><input type="checkbox" /> Confirmo que he leído la declaración y el compromiso descritos en la ficha institucional.</label><div className="field-grid"><FormField label="N.º de cédula del representante" /><FormField label="N.º de cédula del estudiante" placeholder={student.id} /><FormField label="Nombre de la institución" /><FormField label="Fecha" type="date" /></div><div className="signature-box"><span>Espacio para firma del padre de familia o representante legal (o huella digital)</span><div className="signature-line" /><small>Representación visual únicamente · Sin firma electrónica</small></div><FormField label="Observaciones" type="textarea" /></>
  ]
}
