import { FormField, CheckGroup } from '../../components/form-field'
import type { Student } from '../../types/student'
import type { ReactNode } from 'react'

export function createGeneralFormSections(student: Student): ReactNode[] {
  return [
    <><div className="field-grid three"><FormField label="N.º de matrícula" /><FormField label="N.º de cédula" placeholder={student.id} /><FormField label="Año lectivo" placeholder="20__ – 20__" /><FormField label="Año de EGB" required /><FormField label="Apellidos y nombres" required placeholder={student.name} /><FormField label="Lugar de nacimiento" /><FormField label="Fecha de nacimiento" type="date" /><FormField label="Edad" type="number" /><FormField label="Dirección del domicilio" /><FormField label="Sector" /></div><FormField label="Cambio de domicilio" type="textarea" placeholder="Detalle si corresponde" /></>,
    <><h3>Datos de la madre</h3><div className="field-grid three"><FormField label="Nombre de la madre" /><FormField label="Edad" type="number" /><FormField label="Estado civil" /><FormField label="Instrucción" /><FormField label="Profesión u ocupación" /><FormField label="Lugar de trabajo" /></div><h3>Datos del padre</h3><div className="field-grid three"><FormField label="Nombre del padre" /><FormField label="Edad" type="number" /><FormField label="Estado civil" /><FormField label="Instrucción" /><FormField label="Profesión u ocupación" /><FormField label="Lugar de trabajo" /></div><h3>Representante legal, cuidador o tutor</h3><div className="field-grid three"><FormField label="Nombre" /><FormField label="Parentesco" /><FormField label="Edad" type="number" /><FormField label="Profesión u ocupación" /><FormField label="Lugar de trabajo" /><FormField label="Teléfono de contacto" type="tel" /></div><FormField label="Teléfonos de contacto familiares" /></>,
    <><FormField label="Personas con quienes vive el estudiante" type="textarea" /><div className="field-grid three"><FormField label="Número de hermanos" type="number" /><FormField label="Edades de hermanos" /><FormField label="Lugar que ocupa en la familia" type="number" /></div><FormField label="Hermanos que estudian en la institución y edades" type="textarea" /><FormField label="Descripción de la estructura familiar" type="textarea" /><div className="field-grid"><FormField label="¿Familia con algún tipo de discapacidad?" options={['Sí', 'No']} /><FormField label="¿Quién?" /></div></>,
    <><div className="field-grid"><FormField label="Condición de vivienda" options={['Propia', 'Arrendada', 'Prestada', 'Compartida', 'Cedida']} /></div><FormField label="Breve descripción de la vivienda" type="textarea" placeholder="Casa, departamento, cuarto, etc." /><CheckGroup title="Servicios disponibles" items={['Luz', 'Agua potable', 'SSHH', 'Pozo séptico', 'Teléfono', 'Cable', 'Celular', 'Computadora', 'Internet']} /></>,
    <><div className="notice sensitive">Información confidencial. Complete únicamente con información proporcionada por el representante.</div><div className="field-grid"><FormField label="¿Tiene algún tipo de discapacidad?" options={['Sí', 'No']} /><FormField label="Determine cuál" /></div><div className="field-grid"><FormField label="¿Tiene alguna condición médica específica?" options={['Sí', 'No']} /><FormField label="Determine cuál" /></div><div className="field-grid"><FormField label="¿Padece de alergias?" options={['Sí', 'No']} /><FormField label="Especifique alergias" /><FormField label="Medicamentos que utiliza" /></div><FormField label="Atención médica en" options={['Centro de salud', 'Subcentro de salud', 'Hospital público', 'Hospital privado']} /><FormField label="Nombre del centro de salud" /><FormField label="Nombre del médico que atiende regularmente" /></>,
    <><div className="field-grid"><FormField label="Fecha de ingreso a la institución" type="date" /><FormField label="Institución educativa de la que procede" /></div><div className="notice">El representante o padre de familia debe asistir regularmente a la Unidad Educativa para averiguar novedades académicas e inasistencias. Las inasistencias deben justificarse al reincorporarse a clases.</div><div className="signature-row"><div>Representante o padre de familia <span>Firma</span><div className="signature-line" /></div><div>Representante del DECE <span>Firma</span><div className="signature-line" /></div></div></>
  ]
}
